name: pandoc-make-bibs

on: 
  push:
    branches:
      - 'dev/**'
      - 'restructure'
      - 'main'

jobs:
  make_publish_bib:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: create output dir
        id: make_dir
        run: mkdir output
      - uses: docker://pandoc/core:2.9
        with:
          args: >-
            --filter=pandoc-citeproc generatebib.md
            -o output/archivematica-bib.md
            --bibliography archivematica.bib 
      - uses: docker://pandoc/core:2.9
        with:
          args: >-
            --filter=pandoc-citeproc
            --standalone generatebib.md
            -o output/archivematica-bib.html
            --bibliography archivematica.bib
      - name: make README
        run: cat output/archivematica-bib.md intro_placeholder.md > output/README.md      
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./
